dist: trusty
language: java
jdk:
 - oraclejdk8
before_script: 
 - mkdir neo4j_plugins
 - cd neo4j_plugins
 - wget https://github.com/jbarrasa/neosemantics/releases/download/3.5.0.1/neosemantics-3.5.0.1.jar
 - wget https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/3.5.0.1/apoc-3.5.0.1-all.jar
 - cd ..
 - docker-compose up -d
 - cd wmss
