version: '2'
services:
  neo4j:
    container_name: neo4j-wmss
    network_mode: host  
    image: neo4j:3.5.5
    volumes:
      - ./neo4j_plugins:/plugins
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_connectors_default_listen_address=0.0.0.0     
      - NEO4J_dbms_unmanaged_extension_classes=semantics.extension=/rdf
      - NEO4J_AUTH=none   
    ports:
      - 7474:7474
      - 7687:7687
volumes:
  neo4j_plugins:

  
